/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.*;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Khosravi
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idSickLabel = new javax.swing.JLabel();
        idSickField = new javax.swing.JTextField();
        nameSickLabel = new javax.swing.JLabel();
        nameSickField = new javax.swing.JTextField();
        familySickLabel = new javax.swing.JLabel();
        familySickField = new javax.swing.JTextField();
        ageSickLabel = new javax.swing.JLabel();
        ageSickField = new javax.swing.JTextField();
        sexSickLabel = new javax.swing.JLabel();
        illnessSickLabel = new javax.swing.JLabel();
        illnessSickField = new javax.swing.JTextField();
        hsitorySickLabel = new javax.swing.JLabel();
        historySickField = new javax.swing.JTextField();
        createAccountButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        sexSickComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(81, 196, 211));

        jLabel1.setFont(new java.awt.Font("B Titr", 1, 42)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ایجاد حساب کاربری بیمار");

        idSickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        idSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idSickLabel.setText("کد ملی");

        idSickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        idSickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nameSickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        nameSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameSickLabel.setText("نام");

        nameSickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        nameSickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        familySickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        familySickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        familySickLabel.setText("نام خانوادگی");

        familySickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        familySickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ageSickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        ageSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageSickLabel.setText("سن");

        ageSickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        ageSickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sexSickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        sexSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sexSickLabel.setText("جنسیت");

        illnessSickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        illnessSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        illnessSickLabel.setText("شرح بیماری");

        illnessSickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        illnessSickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hsitorySickLabel.setFont(new java.awt.Font("B Titr", 1, 22)); // NOI18N
        hsitorySickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hsitorySickLabel.setText("سوابق بیماری خاص");

        historySickField.setFont(new java.awt.Font("B Titr", 1, 18)); // NOI18N
        historySickField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        createAccountButton.setBackground(new java.awt.Color(170, 216, 211));
        createAccountButton.setFont(new java.awt.Font("B Titr", 1, 30)); // NOI18N
        createAccountButton.setText("ایجاد حساب");
        createAccountButton.setFocusable(false);
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        returnButton.setBackground(new java.awt.Color(170, 216, 211));
        returnButton.setFont(new java.awt.Font("B Titr", 1, 30)); // NOI18N
        returnButton.setText("بازگشت");
        returnButton.setFocusable(false);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        sexSickComboBox.setBackground(new java.awt.Color(170, 216, 211));
        sexSickComboBox.setFont(new java.awt.Font("B Nazanin", 1, 18)); // NOI18N
        sexSickComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "مرد", "زن" }));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(familySickField)
                            .addComponent(sexSickComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(familySickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(sexSickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(idSickField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameSickField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(ageSickField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageSickLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameSickLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(illnessSickField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(illnessSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(historySickField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hsitorySickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idSickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familySickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familySickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexSickComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ageSickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sexSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(illnessSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(illnessSickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hsitorySickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historySickField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        Accountant accountant = new Accountant();
        this.setVisible(false);
        accountant.showPanel();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed

        try {
            if (idSickField.getText().isEmpty() ||
                 nameSickField.getText().isEmpty() ||
                 familySickField.getText().isEmpty() ||
                 ageSickField.getText().isEmpty() ||
                 sexSickComboBox.getSelectedItem().toString().isEmpty()
                    ) {
                JOptionPane.showInternalMessageDialog(null, "همه اطلاعات خواسته شده را وارد کنید.", "پیغام سیستم", 0);
            } else {
                Writer();
            }
        } catch (IOException ex) {
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    public void showPanel() {
        this.setResizable(false);
        this.setVisible(true);
        setCenter();
        setTitle("حسابداری | ایجاد حساب کاربری بیمار");
    }

    public void setCenter() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dimension.width / 2 - this.getSize().width / 2, dimension.height / 2 - this.getSize().height / 2);
    }

    public void Writer() throws IOException {
        String id = this.idSickField.getText();
        String name = this.nameSickField.getText();
        String family = this.familySickField.getText();
        String age = this.ageSickField.getText();
        String sex = this.sexSickComboBox.getSelectedItem().toString();
        String illness = this.illnessSickField.getText();
        String history = this.historySickField.getText();
        SecureRandom random = new SecureRandom();
        int passcodeInt = random.nextInt(90000000) + 10000000;
        String passcode = passcodeInt + "";
        File myFile = new File("src\\main\\database\\sick\\" + id + " - info.txt");
        FileWriter fileWriter = new FileWriter(myFile);
        BufferedWriter writer = new BufferedWriter(fileWriter);
        
        if(!myFile.exists()){
        writer.write(id+"---"+name+"---"+family+"---"+age+"---"+sex+"---"+illness+"---"+history+"---"+passcode);
        writer.flush();
        writer.close();
        JOptionPane.showInternalMessageDialog(null, passcode, "رمز عبور بیمار", 1);
        JOptionPane.showInternalMessageDialog(null, "حساب کاربری با موفقیت ساخته شد.", "پیغام سیستم", 1);
        } else {
            JOptionPane.showMessageDialog(null, "کاربری با این کدملی وجود دارد.", "پیغام سیستم", 0);
            System.out.println(passcode);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageSickField;
    private javax.swing.JLabel ageSickLabel;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JTextField familySickField;
    private javax.swing.JLabel familySickLabel;
    private javax.swing.JTextField historySickField;
    private javax.swing.JLabel hsitorySickLabel;
    private javax.swing.JTextField idSickField;
    private javax.swing.JLabel idSickLabel;
    private javax.swing.JTextField illnessSickField;
    private javax.swing.JLabel illnessSickLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameSickField;
    private javax.swing.JLabel nameSickLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> sexSickComboBox;
    private javax.swing.JLabel sexSickLabel;
    // End of variables declaration//GEN-END:variables
}
