/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.gui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khosravi
 */
public class SickShowBill extends javax.swing.JFrame {

    /**
     * Creates new form ShowBill
     */
    public SickShowBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        billSickLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        returnButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        sumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(81, 196, 211));

        billSickLabel.setFont(new java.awt.Font("B Titr", 1, 42)); // NOI18N
        billSickLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billSickLabel.setText("صورتحساب بیمار");

        billTable.setBackground(new java.awt.Color(0, 173, 181));
        billTable.setFont(new java.awt.Font("B Nazanin", 1, 20)); // NOI18N
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "صورتحساب"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billTable.setFocusable(false);
        billTable.setRowHeight(24);
        jScrollPane1.setViewportView(billTable);

        returnButton.setBackground(new java.awt.Color(170, 216, 211));
        returnButton.setFont(new java.awt.Font("B Titr", 1, 28)); // NOI18N
        returnButton.setText("بازگشت");
        returnButton.setFocusable(false);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        payButton.setBackground(new java.awt.Color(170, 216, 211));
        payButton.setFont(new java.awt.Font("B Titr", 1, 28)); // NOI18N
        payButton.setText("پرداخت");
        payButton.setFocusable(false);
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        sumLabel.setFont(new java.awt.Font("B Nazanin", 1, 24)); // NOI18N
        sumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sumLabel.setText("مبلغ قابل پرداخت: ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(billSickLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(billSickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        SickAccount sickAccount = new SickAccount();
        this.setVisible(false);
        try {
            sickAccount.showPanel();
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        JOptionPane.showMessageDialog(null, "صورتحساب با موفقیت پرداخت شد.", "پیخام سیستم", 1);
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountantShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountantShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountantShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountantShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountantShowBill().setVisible(true);
            }
        });
    }

    public void showPanel() throws IOException {
        this.setResizable(false);
        this.setVisible(true);
        setCenter();
        setFont();
        showSickName();
        billReader();
        showSum(getSum());
        rightAlignment();
        setTitle("بیمار | صورتحساب بیمار");
    }

    public void setCenter() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dimension.width / 2 - this.getSize().width / 2, dimension.height / 2 - this.getSize().height / 2);
    }

    public void billReader() throws FileNotFoundException, IOException {
        int sum = 0;
        String id = Sick.idSickField.getText();
        File billFile = new File("src\\main\\database\\sick\\" + id + " - bill.txt");
        FileReader billFileReader = new FileReader(billFile);
        BufferedReader billReader = new BufferedReader(billFileReader);
        String text = "";
        String line;
        while ((line = billReader.readLine()) != null) {
            text += line + ";";
        }
        billReader.close();
        String[] info = text.split(";");
        int[] bill = new int[info.length];
        for (int i = 0; i < info.length; i++) {
            bill[i] = Integer.parseInt(info[i]);
        }
        for (int i = 0; i < bill.length; i++) {
            sum += bill[i];
        }
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        for (int i = 0; i < bill.length; i++) {
            if (bill[i] == 100000) {
                model.addRow(new Object[]{"داروی شماره 1: " + bill[i]});
            } else if (bill[i] == 200000) {
                model.addRow(new Object[]{"داروی شماره 2: " + bill[i]});
            } else if (bill[i] == 300000) {
                model.addRow(new Object[]{"داروی شماره 3: " + bill[i]});
            } else if (bill[i] == 400000) {
                model.addRow(new Object[]{"داروی شماره 4: " + bill[i]});
            } else if (bill[i] == 500000) {
                model.addRow(new Object[]{"عمل جراحی: " + bill[i]});
            } else if (bill[i] == 50000) {
                model.addRow(new Object[]{"معالجه پزشک: " + bill[i]});
            }
        }
    }

    public int getSum() throws FileNotFoundException, IOException {
        int sum = 0;
        String id = Sick.idSickField.getText();
        File billFile = new File("src\\main\\database\\sick\\" + id + " - bill.txt");
        FileReader billFileReader = new FileReader(billFile);
        BufferedReader billReader = new BufferedReader(billFileReader);
        String text = "";
        String line;
        while ((line = billReader.readLine()) != null) {
            text += line + ";";
        }
        billReader.close();
        String[] info = text.split(";");
        int[] bill = new int[info.length];
        for (int i = 0; i < info.length; i++) {
            bill[i] = Integer.parseInt(info[i]);
        }
        for (int i = 0; i < bill.length; i++) {
            sum += bill[i];
        }
        return sum;
    }

    public void showSickName() throws FileNotFoundException, IOException {
        String id = Sick.idSickField.getText();

        File file = new File("src\\main\\database\\sick\\" + id + " - info.txt");
        FileReader fileReader = new FileReader(file);
        BufferedReader reader = new BufferedReader(fileReader);
        
        String text = "";
        String line;
        while((line = reader.readLine()) != null){
            text += line + "---";
        }
        
        String[] data = text.split("---");

        billSickLabel.setText("صورتحساب " + data[1] + " " + data[2]);
    }

    public void setFont() {
        Font font = new Font("B Titr", Font.BOLD, 20);
        billTable.getTableHeader().setFont(font);
    }

    public void rightAlignment() {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
        billTable.getColumn("صورتحساب").setCellRenderer(rightRenderer);
    }

    public void showSum(int sum) throws IOException {
        sumLabel.setText("مبلغ قابل پرداخت: " + sum);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billSickLabel;
    private javax.swing.JTable billTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton payButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel sumLabel;
    // End of variables declaration//GEN-END:variables
}
